####################
## Configurations ##
####################
language: r
r: 3.5.2
r_packages:
  - tidyverse
sudo: false
latex: false
fortran: true
cache: packages
stages:
  - info
  - build
  #- test-suite
  #- code-quality
  #- deploy
# Be strict when checking the package?
warnings_are_errors: false


#######################
## Build the Package ##
#######################
jobs:
  include:
    - state: "Info"
    name: "System Information"
    script: Rscript --vanilla -e 'print(Sys.getenv())'
    name: "Installed Packages"
    script: Rscript --vanilla -e 'print(unname(installed.packages()[,c("Package", "Version")]))'
    - stage: "Build"
    name: "Build and Check"
    script:
      - R CMD build . --no-build-vignettes --no-manual
      - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-manual
