# tic documentation: https://docs.ropensci.org/tic/dev/

# OS ---------------------------------------------------------------------------
os: linux
dist: bionic

# meta -------------------------------------------------------------------------
language: r
cache:
  - packages
  - $HOME/.ccache
latex: false

env:
  global:
  - MAKEFLAGS="-j 2"

# multiple R versions ----------------------------------------------------------
matrix:
  #allow_failures:
  #- r: oldrel
  include:
  #- r: devel
  #- r: oldrel
  - r: release

# Stages -----------------------------------------------------------------------

# DO NOT CHANGE THE CODE BELOW -------------------------------------------------
before_install:
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic@v0.3.0"); print(tic::dsl_load()); tic::prepare_all_stages()'
  - R -q -e 'tic::before_install()'
install: R -q -e 'tic::install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE -------------------------------------------------
