####################
## Configurations ##
####################
# Be strict when checking the package?
warnings_are_errors: false
language: r
r: 3.5.2
r_packages:
  - tidyverse
  - devtools
  - testthat
  - covr
sudo: false
latex: false
fortran: true
cache: packages
stages:
  - Build
  - Test-Suite
  - Report
before_script: Rscript -e 'Sys.getenv()'
after_success: Rscript -e 'message("Silence is Golden")'

#######################
## Build the Package ##
#######################
jobs:
  include:
    - stage: "Build"
      name: "build-and-Check"
      script: Rscript --vanilla .github-ci/build-and-check.R
    - stage: "Test-Suite"
      name: "testthat"
      script: Rscript --vanilla .github-ci/test-suite.R
    - stage: "Test-Suite"
      name: "component-tests"
      script: Rscript --vanilla .github-ci/test-suite.R
    - stage: "Test-Suite"
      name: "integration-tests"
      script: Rscript --vanilla .github-ci/test-suite.R
    - stage: "Test-Suite"
      name: "coverage-tests"
      script: Rscript --vanilla .github-ci/test-suite.R
    - stage: "Report"
      name: "coverage-report"
      script: Rscript -e 'covr::codecov()'
