# tic documentation: https://docs.ropensci.org/tic/dev/

# OS ---------------------------------------------------------------------------
os: linux
dist: bionic

# meta -------------------------------------------------------------------------
language: r
cache:
  - packages
  - $HOME/.ccache
latex: false

env:
  global:
  - MAKEFLAGS="-j 2"

# multiple versions ------------------------------------------------------------
r: 3.6.2

# stages -----------------------------------------------------------------------
stages:
  - build
  - test
  - deploy
#    if: branch = master

# jobs -------------------------------------------------------------------------
jobs:
  include:
    - stage: "build"
      name: "build"
      script: R -q -e 'tic::script()'
    - stage: "test"
      name: "testthat"
      script: R -q -e 'tic::script()'
    - stage: "test"
      name: "component-tests"
      script: R -q -e 'tic::script()'
    - stage: "test"
      name: "integration-tests"
      script: R -q -e 'tic::script()'
    - stage: "test"
      name: "coverage-tests"
      script: R -q -e 'tic::script()'
    - stage: "deploy"
      name: "coverage-report"
      script: R -q -e 'tic::script()'
    - stage: "deploy"
      name: "pkgdown"
      script: R -q -e 'tic::script()'

# DO NOT CHANGE THE CODE BELOW -------------------------------------------------
before_install:
  - R -q -e 'if(!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic@v0.3.0"); print(tic::dsl_load()); tic::prepare_all_stages()'
  - R -q -e 'tic::before_install()'
install: R -q -e 'tic::install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
#     branch: master
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE -------------------------------------------------
