####################
## Configurations ##
####################
# Be strict when checking the package?
warnings_are_errors: false
language: r
r: 3.5.2
r_packages:
  - tidyverse
  - covr
sudo: false
latex: false
fortran: true
cache: packages
stages:
  - Build
before_script:
  - Rscript -e 'Sys.getenv()'
after_success:
  - Rscript -e 'library(covr); codecov()'


#######################
## Build the Package ##
#######################
jobs:
  include:
    - stage: "Build"
      name: "Build and Check"
      script:
        - Rscript --vanilla .githab-ci/build_and_check.R
